---
version: "2.1"
services:
  yt-archive-channels:
    container_name: yt-archive-channels
    image: zibbp/yt-archive-docker:latest
    user: 1000:1000
    environment:
      - MODE=Channels
    volumes:
      - /path/to/yt-archive/container-scripts:/opt/app/scripts
      - /path/to/yt-archive/output-Channels:/opt/app/output
      - /mnt/vault/videos/YouTube:/mnt/videos
  yt-archive-playlists:
    container_name: yt-archive-playlists
    image: zibbp/yt-archive-docker:latest
    user: 1000:1000
    environment:
      - MODE=Playlists
    volumes:
      - /path/to/yt-archive/container-scripts:/opt/app/scripts
      - /path/to/yt-archive/output-Playlists:/opt/app/output
      - /mnt/vault/videos/YouTube:/mnt/videos
  yt-archive-unique:
    container_name: yt-archive-unique
    image: zibbp/yt-archive-docker:latest
    user: 1000:1000
    environment:
      - MODE=Unique
    volumes:
      - /path/to/yt-archive/container-scripts:/opt/app/scripts
      - /path/to/yt-archive/output-Unique:/opt/app/output
      - /mnt/vault/videos/YouTube:/mnt/videos
