---
version: "2.1"
services:
  yt-archive-channels:
    container_name: yt-archive-channels
    image: zibbp/yt-archive-docker:latest
    user: 1000:1000
    environment:
      - MODE=Channels
    volumes:
      - ./channels-data:/data
      # output is bound to the host incase connection to nas is unavailable
      - ./channels-output:/opt/app/output
      - /mnt/vault/videos/YouTube:/mnt/videos
  yt-archive-playlists:
    container_name: yt-archive-playlists
    image: zibbp/yt-archive-docker:latest
    user: 1000:1000
    environment:
      - MODE=Playlists
    volumes:
      - ./playlists-data:/data
      - ./playlists-output:/opt/app/output
      - /mnt/vault/videos/YouTube:/mnt/videos
  yt-archive-unique:
    container_name: yt-archive-unique
    image: zibbp/yt-archive-docker:latest
    user: 1000:1000
    environment:
      - MODE=Unique
    volumes:
      - ./unique-data:/data
      - ./unique-output:/opt/app/output
      - /mnt/vault/videos/YouTube:/mnt/videos
